name: Daily Dispatch Email

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST (4 AM UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  email-dispatch-report:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      RECIPIENT: ${{ secrets.RECIPIENT }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install fpdf pandas

    - name: Run daily dispatch email
      run: python3 daily_dispatch_email.py

