name: Daily Dispatch Email

on:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST = 3:00 AM UTC
  workflow_dispatch:  # Allow manual run if needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fpdf2

      - name: Run email dispatch script
        run: |
          python scripts/email_dispatch_report.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
