name: Daily Dispatch Email

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 9:00 AM IST
  workflow_dispatch:

jobs:
  send-dispatch-report:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      RECIPIENT: ${{ secrets.RECIPIENT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install fpdf pandas

      - name: Generate Dispatch PDF
        run: |
          python generate_dispatch_pdf.py

      - name: Send Dispatch Email
        run: |
          python send_dispatch_email.py

