name: Daily Dispatch Email Report

on:
  schedule:
    - cron: '0 4 * * *'  # This is UTC time, 4:00 AM UTC = 9:30 AM IST
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  dispatch-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Dispatch Email Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH
        SNOWFLAKE_DATABASE: ORDERS_DB
        SNOWFLAKE_SCHEMA: ORDERS_SCHEMA
        SNOWFLAKE_ROLE: ACCOUNTADMIN
      run: |
        python scripts/dispatch_email.py
