name: Daily Dispatch Email Report

on:
  workflow_dispatch:  # Manual run button
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST (adjust if needed)

jobs:
  dispatch-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Dispatch Email Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH
        SNOWFLAKE_DATABASE: ORDERS_DB
        SNOWFLAKE_SCHEMA: ORDERS_SCHEMA
        SNOWFLAKE_ROLE: ACCOUNTADMIN
      run: |
        echo "🔄 Starting Dispatch Email Report..."
        python scripts/dispatch_email.py

